In [1]:
println("Hello World")

Hello World


In [2]:
5+5

10

In [5]:
println(5-3.8, " this is decimal")

1.2000000000000002 this is decimal


In [7]:
print("Hello"*" World")

Hello World

In [9]:
print("Hello "^3)

Hello Hello Hello 

In [10]:
5 + 9 # 14

14

In [14]:
?print

search: print println printstyled sprint isprint prevind parentindices precision



```
print([io::IO], xs...)
```

Write to `io` (or to the default output stream [`stdout`](@ref) if `io` is not given) a canonical (un-decorated) text representation of values `xs` if there is one, otherwise call [`show`](@ref). The representation used by `print` includes minimal formatting and tries to avoid Julia-specific details.

Printing `nothing` is not allowed and throws an error.

# Examples

```jldoctest
julia> print("Hello World!")
Hello World!
julia> io = IOBuffer();

julia> print(io, "Hello", ' ', :World!)

julia> String(take!(io))
"Hello World!"
```


In [15]:
1 - 2 + 3 - 4

-2

In [16]:
1 / 2 + 3 / 4

1.25

In [17]:
1 / (2 + 3) / 4

0.05

In [18]:
1 / (2 + 3 / 4)

0.36363636363636365

In [19]:
(1 / 2 + 3) / 4

0.875

In [20]:
print(1/2/3)

0.16666666666666666

In [21]:
print(2-3+4)

3

In [22]:
println(2/3^2)

0.2222222222222222


In [23]:
println(3-2/4)

2.5


In [24]:
println(3+2*9-6)

15


In [25]:
0.2 + 0.1 - 3 * 6.7 / 4 - 1 - 2 * 3 #bad becoz mixes float and int

-11.725000000000001

In [26]:
0.2 + 0.1 - ((3 * 6.7) / 4) - 1 - (2 * 3) #L-R

-11.725000000000001

In [27]:
0.2 + 0.1 - 5.025 - 1 - 6

-11.725000000000001

In [28]:
println(3^2^3) #R-L
println((3^2)^3) #forcing L-R using paranth

6561
729


In [29]:
!true #false
!false

true

In [30]:
true && true

true

In [31]:
false && true

false

In [32]:
true && false

false

In [33]:
false && false

false

In [34]:
true || true #true
false || true #true
true || false

true

In [35]:
false || false

false

In [36]:
1 < 22

true

In [37]:
-10 > 3

false

In [38]:
2 == 4-2

true

In [39]:
(3-4 > 1) && (2+2 == 4) || (10-5 > 2)

true

In [40]:
false && true || true

true

In [41]:
5040 / 60

84.0

In [42]:
2*3+2^1+1

9

In [43]:
0-6+2^4

10

In [44]:
2^2+6

10

In [45]:
8+2*3-3

11

In [49]:
(3.0 < 4)&&(4 < 5.0)

true

In [50]:
(true || false) && false

false

In [51]:
3 & 5 > 0

true

In [52]:
8 & 5 > 0

false

In [54]:
1 + 2 - (5 - 2) == 0

true

In [55]:
typeof(1)

Int64

In [56]:
typeof("Hello World!")

String

In [57]:
typeof("H")

String

In [58]:
typeof('H')

Char

In [59]:
typeof(1+3+5.)

Float64

In [62]:
println("αβ±⋄") 

αβ±⋄


In [64]:
typeof(true)

Bool

In [65]:
2.0 == 2

true

In [66]:
2 < 3/2

false

In [67]:
2.0 === 2

false

In [69]:
Array{Int64}(undef, 3) #creates 3x1 julia hates empty array so it generates numbers randomly
#3 is number of elements

3-element Array{Int64,1}:
 147748448
 255632880
 260295504

In [70]:
Array{Int64, 1}(undef, 3) # is dimentions

3-element Array{Int64,1}:
 147638480
  90877408
 260306832

In [71]:
Array{String}(undef, 3)

3-element Array{String,1}:
 #undef
 #undef
 #undef

In [73]:
greeting = "Madhuri"
println("Hello "*greeting)

Hello Madhuri


In [74]:
abstypevariable = Array{Integer}(undef, 2, 3) 
#2d array with 2rows and 3 columns

2×3 Array{Integer,2}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [75]:
typeof(abstypevariable)

Array{Integer,2}

In [76]:
abstypevariable[1,1] = 1

1

In [77]:
abstypevariable[1,2] = 2

2

In [78]:
abstypevariable

2×3 Array{Integer,2}:
   1       2     #undef
 #undef  #undef  #undef

In [79]:
abstypevariable[1,3] = 5.0

5.0

In [80]:
abstypevariable

2×3 Array{Integer,2}:
   1       2       5   
 #undef  #undef  #undef

In [81]:
arbconcretevariable = Array{Int64}(undef, 2, 3)

2×3 Array{Int64,2}:
 236191752  265580368  265580432
 265580304  265580400  267628656

In [82]:
'a'==="a"

false

In [83]:
x = Array{Int64}(undef,11, 12)

11×12 Array{Int64,2}:
 286250160  246549376  246550048  …  246555472  246556912  246557440
 286250208  246549424  246550096     246555520  246556960  246557488
 286250256  246549568  246550144     246555568  246557008  246557536
 286250304  246549616  246550192     246555616  246557056  246557584
 286250352  246549664  246550240     246555664  246557104  246557632
 286250400  246549712  246550288  …  246555712  246557152  246557680
 286250448  246549760  246550336     246555808  246557200  246559504
 286250496  246549856  246551200     246556624  246557248          0
 286250544  246549904  246551248     246556672  246557296          0
 246549280  246549952  246551344     246556816  246557344          0
 246549328  246550000  246551392  …  246556864  246557392          0

In [84]:
typeof(x)

Array{Int64,2}

In [85]:
a, b, c = cos(0.2), log(10), abs(-1.22) #multiple assignments

(0.9800665778412416, 2.302585092994046, 1.22)

In [86]:
a

0.9800665778412416

In [87]:
? cos

search: cos cosh cosd cosc cospi acos acosh acosd sincos const close isconst



```
cos(x)
```

Compute cosine of `x`, where `x` is in radians.

---

```
cos(A::AbstractMatrix)
```

Compute the matrix cosine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the cosine. Otherwise, the cosine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> cos(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
  0.291927  -0.708073
 -0.708073   0.291927
```


In [88]:
?help

search: schedule Channel @threadcall AbstractChannel searchsortedlast



**Welcome to Julia 1.0.5.** The full manual is available at

```
https://docs.julialang.org/
```

as well as many great tutorials and learning resources:

```
https://julialang.org/learning/
```

For help on a specific function or macro, type `?` followed by its name, e.g. `?cos`, or `?@time`, and press enter. Type `;` to enter shell mode, `]` to enter package mode.


In [89]:
methods(muladd)

# 12 methods for generic function "muladd":
[1] muladd(a::Float16, b::Float16, c::Float16) in Base at float.jl:406
[2] muladd(x::Float64, y::Float64, z::Float64) in Base at float.jl:404
[3] muladd(x::Float32, y::Float32, z::Float32) in Base at float.jl:403
[4] muladd(z::Complex, w::Complex, x::Complex) in Base at complex.jl:271
[5] muladd(x::Real, z::Complex, y::Number) in Base at complex.jl:314
[6] muladd(z::Complex, x::Real, y::Real) in Base at complex.jl:315
[7] muladd(z::Complex, x::Real, w::Complex) in Base at complex.jl:316
[8] muladd(x::Real, y::Real, z::Complex) in Base at complex.jl:318
[9] muladd(z::Complex, w::Complex, x::Real) in Base at complex.jl:319
[10] muladd(x::T, y::T, z::T) where T<:Number in Base at promotion.jl:419
[11] muladd(x::Number, y::Number, z::Number) in Base at promotion.jl:348
[12] muladd(x, y, z) in Base.Math at math.jl:1011

In [90]:
myfunc(var) = 20*var

myfunc (generic function with 1 method)

In [91]:
myfunc(333.2222) # calling a function

6664.4439999999995

In [92]:
addxtoy(x,y) = x+y

addxtoy (generic function with 1 method)

In [93]:
addxtoy(33, -22.2)

10.8

In [94]:
function multilinefunc(a,b,c)
    a*b+c
end

multilinefunc (generic function with 1 method)

In [95]:
multilinefunc(7,5,3)

38

In [99]:
function showdebugprintln(var)
    println("inside the showdebugprint() now")
    println("The type of var is $(typeof(var)) and the value of var is $var")
end

showdebugprintln (generic function with 1 method)

In [100]:
a = ['1', 2.]
showdebugprintln(a)

inside the showdebugprint() now
The type of var is Array{Any,1} and the value of var is Any['1', 2.0]


In [101]:
mycos(x) = cos(x)

mycos (generic function with 1 method)

In [102]:
mycos(.7)

0.7648421872844885

In [103]:
mycos(adj, hyp) = adj/hyp

mycos (generic function with 2 methods)

In [104]:
mycos(12,13)

0.9230769230769231

In [105]:
methods(mycos)

# 2 methods for generic function "mycos":
[1] mycos(x) in Main at In[101]:1
[2] mycos(adj, hyp) in Main at In[103]:1

In [106]:
mycos(thet::Float64) = cos(thet)

mycos (generic function with 3 methods)

In [107]:
?/

search: / //



```
/(x, y)
```

Right division operator: multiplication of `x` by the inverse of `y` on the right. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 1/2
0.5

julia> 4/2
2.0

julia> 4.5/2
2.25
```


In [108]:
?\

search: \



```
\(x, y)
```

Left division operator: multiplication of `y` by the inverse of `x` on the left. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 3 \ 6
2.0

julia> inv(3) * 6
2.0

julia> A = [4 3; 2 1]; x = [5, 6];

julia> A \ x
2-element Array{Float64,1}:
  6.5
 -7.0

julia> inv(A) * x
2-element Array{Float64,1}:
  6.5
 -7.0
```

---

```
\(A, B)
```

Matrix division using a polyalgorithm. For input matrices `A` and `B`, the result `X` is such that `A*X == B` when `A` is square. The solver that is used depends upon the structure of `A`.  If `A` is upper or lower triangular (or diagonal), no factorization of `A` is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular `A` the result is the minimum-norm least squares solution computed by a pivoted QR factorization of `A` and a rank estimate of `A` based on the R factor.

When `A` is sparse, a similar polyalgorithm is used. For indefinite matrices, the `LDLt` factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

# Examples

```jldoctest
julia> A = [1 0; 1 -2]; B = [32; -4];

julia> X = A \ B
2-element Array{Float64,1}:
 32.0
 18.0

julia> A * X == B
true
```

---

```
(\)(F::QRSparse, B::StridedVecOrMat)
```

Solve the least squares problem $\min\|Ax - b\|^2$ or the linear system of equations $Ax=b$ when `F` is the sparse QR factorization of $A$. A basic solution is returned when the problem is underdetermined.

# Examples

```jldoctest
julia> A = sparse([1,2,4], [1,1,1], [1.0,1.0,1.0], 4, 2)
4×2 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [2, 1]  =  1.0
  [4, 1]  =  1.0

julia> qr(A)\fill(1.0, 4)
2-element Array{Float64,1}:
 1.0
 0.0
```


In [109]:
addone(x::Int64) = x+1

addone (generic function with 1 method)

In [112]:
addone(10)

11

In [114]:
a,b = 1,2

b = a

a = b
print(a)

1

In [115]:
function test(input)
  println("$input"^2)
end

test(2)

22


In [116]:
add2(x,y) = x+y
print(add2(5,7))

12

In [118]:
add2(x,y) = return x+y
print(add2(5,7))

12

In [119]:
function coordinates(x, y=0, z=0)
  println("($x, $y, $z)")
end

coordinates (generic function with 3 methods)

In [122]:
coordinates(1,0,2)

(1, 0, 2)


In [126]:
(2^3)^2-500

-436

In [124]:
println("$(2*6)")

12


In [125]:
2^2^1^5+2^3

12

In [129]:
(5 - 7) * 2 + 4

0

In [130]:
1 + 3 < 5 && 2^2 === 4.0

false

In [132]:
3 > 0 && 3 <= 3

true

In [137]:
true && (false && (false || true))

false

In [138]:
matrix = Array{Float64,2}(undef, a, b)

1×1 Array{Float64,2}:
 1.305348393e-315

In [139]:
function f(x)
  return 2x
  3x
end

f (generic function with 1 method)

In [140]:
f(5)

10